Repository playdata-final-project-team/Wesell, pull requests merged in 2023-12, with the labels that each got.

#90 feat: 유저 검색 기능 구현
  admin-service/src/main/java/com/wesell/adminservice/controller/AdminController.java
  admin-service/src/main/java/com/wesell/adminservice/dto/response/AdminUserResponseDto.java
  admin-service/src/main/java/com/wesell/adminservice/feignClient/UserFeignClient.java
  admin-service/src/main/java/com/wesell/adminservice/service/AdminService.java
  admin-service/src/main/java/com/wesell/adminservice/service/VersionService.java
  admin-service/src/main/resources/application.yml
  authentication-server/src/main/java/com/wesell/authenticationserver/controller/AdminAuthController.java
  user-service/src/main/java/com/wesell/userservice/controller/AdminUserController.java
  user-service/src/main/java/com/wesell/userservice/domain/repository/AdminUserRepository.java
  user-service/src/main/java/com/wesell/userservice/dto/request/AdminUserRequestDto.java
  user-service/src/main/java/com/wesell/userservice/dto/response/AdminUserResponseDto.java
  user-service/src/main/java/com/wesell/userservice/service/AdminUserService.java
Labels: feat

#95 [User] - 비밀번호 찾기 기능 구현
  authentication-server/build.gradle
  authentication-server/src/main/java/com/wesell/authenticationserver/controller/CertificatePhoneController.java
  authentication-server/src/main/java/com/wesell/authenticationserver/controller/FindIDFeignController.java
  authentication-server/src/main/java/com/wesell/authenticationserver/controller/FindPWDFeignController.java
  authentication-server/src/main/java/com/wesell/authenticationserver/controller/dto/request/FindIDRequestDto.java
  authentication-server/src/main/java/com/wesell/authenticationserver/controller/dto/request/FindPWDRequestDto.java
  authentication-server/src/main/java/com/wesell/authenticationserver/domain/entity/AuthUser.java
  authentication-server/src/main/java/com/wesell/authenticationserver/domain/repository/FindIDRepository.java
  authentication-server/src/main/java/com/wesell/authenticationserver/domain/repository/FindPWDRepository.java
  authentication-server/src/main/java/com/wesell/authenticationserver/exception/InvalidCodeException.java
  authentication-server/src/main/java/com/wesell/authenticationserver/exception/UserNotFoundException.java
  authentication-server/src/main/java/com/wesell/authenticationserver/global/util/SmsUtil.java
  authentication-server/src/main/java/com/wesell/authenticationserver/service/feign/UserServiceFeignClient.java
  authentication-server/src/main/java/com/wesell/authenticationserver/service/userservice/FindIDFeignService.java
  authentication-server/src/main/java/com/wesell/authenticationserver/service/userservice/FindPWDFeignService.java
  authentication-server/src/main/resources/application.yml
  user-service/src/main/java/com/wesell/userservice/controller/CertificatePhoneController.java
  user-service/src/main/java/com/wesell/userservice/controller/FeignController.java
  user-service/src/main/java/com/wesell/userservice/controller/FindIDController.java
  user-service/src/main/java/com/wesell/userservice/dto/response/FindIDResponseDto.java
  user-service/src/main/java/com/wesell/userservice/service/FindIDService.java
  user-service/src/main/java/com/wesell/userservice/service/UserService.java
  user-service/src/main/java/com/wesell/userservice/service/feign/AuthServerFeignClient.java
  user-service/src/main/resources/application.yml
Labels: feat

#96 feat:[Front] Front-server & API-Gateway-server CORS 설정
  .idea/Wesell.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  .idea/workspace.xml
  apigateway-server/src/main/java/com/wesell/apigatewayserver/filter/AuthorizationCheckFilter.java
  apigateway-server/src/main/resources/application.yml
  authentication-server/src/main/java/com/wesell/authenticationserver/controller/AdminAuthController.java
  authentication-server/src/main/java/com/wesell/authenticationserver/controller/AuthController.java
  authentication-server/src/main/java/com/wesell/authenticationserver/controller/CorsTestController.java
  authentication-server/src/main/java/com/wesell/authenticationserver/domain/entity/AuthUser.java
  authentication-server/src/main/java/com/wesell/authenticationserver/service/feign/UserServiceFeignClient.java
  authentication-server/src/main/resources/application.yml
  front-server/.env
  front-server/package-lock.json
  front-server/package.json
  front-server/src/App.tsx
  front-server/src/apis/index.ts
  front-server/src/components/CheckBox/index.tsx
  front-server/src/components/InputBox/index.tsx
  front-server/src/pages/Authentication/index.tsx
  front-server/src/pages/Test/index.tsx
  front-server/tsconfig.json
Labels: feat

#101 fix: Admin-sever 회원 목록 조회 feign 요청 경로 수정
  authentication-server/src/main/java/com/wesell/authenticationserver/controller/AuthController.java
  authentication-server/src/main/java/com/wesell/authenticationserver/controller/response/CustomException.java
  authentication-server/src/main/java/com/wesell/authenticationserver/controller/response/ErrorCode.java
  authentication-server/src/main/java/com/wesell/authenticationserver/controller/response/ErrorControllerAdvisor.java
  authentication-server/src/main/java/com/wesell/authenticationserver/controller/response/ResponseDto.java
  authentication-server/src/main/java/com/wesell/authenticationserver/controller/response/SuccessCode.java
  authentication-server/src/main/java/com/wesell/authenticationserver/controller/usercontroller/EmailInfoController.java
  authentication-server/src/main/java/com/wesell/authenticationserver/global/util/CustomCookie.java
  authentication-server/src/main/java/com/wesell/authenticationserver/response/ErrorCode.java
  authentication-server/src/main/java/com/wesell/authenticationserver/response/ErrorResponseDto.java
  authentication-server/src/main/java/com/wesell/authenticationserver/response/SuccessCode.java
  authentication-server/src/main/java/com/wesell/authenticationserver/service/AuthUserService.java
  user-service/src/main/java/com/wesell/userservice/service/feign/AuthServerFeignClient.java
Labels: wontfix

#103 feat: 페이징 처리 구현
  admin-service/src/main/java/com/wesell/adminservice/controller/AdminController.java
  admin-service/src/main/java/com/wesell/adminservice/dto/response/UserListResponseDto.java
  admin-service/src/main/java/com/wesell/adminservice/feignClient/DealFeignClient.java
  admin-service/src/main/java/com/wesell/adminservice/feignClient/UserFeignClient.java
  admin-service/src/main/java/com/wesell/adminservice/service/AdminService.java
  deal-service/src/main/java/com/wesell/dealservice/controller/AdminDealController.java
  deal-service/src/main/java/com/wesell/dealservice/domain/repository/AdminDealRepository.java
  deal-service/src/main/java/com/wesell/dealservice/service/AdminDealService.java
  deal-service/src/main/resources/application.yml
  user-service/src/main/java/com/wesell/userservice/controller/AdminUserController.java
  user-service/src/main/java/com/wesell/userservice/domain/repository/AdminUserRepository.java
  user-service/src/main/java/com/wesell/userservice/service/AdminUserService.java
Labels: feat

#107 feat: 마이페이지 email FeignTest 및 softdelete 구현
  authentication-server/src/main/java/com/wesell/authenticationserver/controller/AdminAuthController.java
  authentication-server/src/main/java/com/wesell/authenticationserver/controller/AuthFeignController.java
  authentication-server/src/main/java/com/wesell/authenticationserver/controller/CertificatePhoneController.java
  authentication-server/src/main/java/com/wesell/authenticationserver/controller/response/ResponseDto.java
  authentication-server/src/main/java/com/wesell/authenticationserver/domain/entity/AuthUser.java
  authentication-server/src/main/java/com/wesell/authenticationserver/domain/repository/FindIDRepository.java
  authentication-server/src/main/java/com/wesell/authenticationserver/domain/repository/FindPWDRepository.java
  authentication-server/src/main/java/com/wesell/authenticationserver/global/util/CustomConverter.java
  authentication-server/src/main/java/com/wesell/authenticationserver/global/util/SmsUtil.java
  authentication-server/src/main/java/com/wesell/authenticationserver/service/AuthUserService.java
  authentication-server/src/main/java/com/wesell/authenticationserver/service/token/TokenProvider.java
  authentication-server/src/main/java/com/wesell/authenticationserver/service/userservice/FindIDFeignService.java
  user-service/src/main/java/com/wesell/userservice/controller/AdminUserController.java
  user-service/src/main/java/com/wesell/userservice/controller/FeignController.java
  user-service/src/main/java/com/wesell/userservice/controller/UserController.java
  user-service/src/main/java/com/wesell/userservice/controller/UserControllerByChaelim.java
  user-service/src/main/java/com/wesell/userservice/domain/entity/User.java
  user-service/src/main/java/com/wesell/userservice/service/AdminUserService.java
  user-service/src/main/java/com/wesell/userservice/service/feign/AuthServerFeignClient.java
  user-service/src/main/resources/application.yml
Labels: feat

#108 feat: 페이징 처리 및 프론트 카테고리 드롭박스 구현
  deal-service/src/main/java/com/wesell/dealservice/controller/CategoryController.java
  deal-service/src/main/java/com/wesell/dealservice/controller/DealController.java
  deal-service/src/main/java/com/wesell/dealservice/domain/dto/request/CreateCategoryRequestDto.java
  deal-service/src/main/java/com/wesell/dealservice/domain/dto/request/EditPostRequestDto.java
  deal-service/src/main/java/com/wesell/dealservice/domain/dto/request/UploadDealPostRequestDto.java
  deal-service/src/main/java/com/wesell/dealservice/domain/dto/response/CategoryListResponseDto.java
  deal-service/src/main/java/com/wesell/dealservice/domain/dto/response/EditPostResponseDto.java
  deal-service/src/main/java/com/wesell/dealservice/domain/dto/response/ErrorResponseDto.java
  deal-service/src/main/java/com/wesell/dealservice/domain/dto/response/MainPageCategoryResponseDto.java
  deal-service/src/main/java/com/wesell/dealservice/domain/dto/response/MainPagePostResponseDto.java
  deal-service/src/main/java/com/wesell/dealservice/domain/dto/response/MyPostListResponseDto.java
  deal-service/src/main/java/com/wesell/dealservice/domain/dto/response/PostInfoResponseDto.java
  deal-service/src/main/java/com/wesell/dealservice/domain/entity/DealPost.java
  deal-service/src/main/java/com/wesell/dealservice/domain/repository/DealRepository.java
  deal-service/src/main/java/com/wesell/dealservice/dto/facade/MainPageInfoFacadeDto.java
  deal-service/src/main/java/com/wesell/dealservice/error/ControllerAdvisor.java
  deal-service/src/main/java/com/wesell/dealservice/error/ErrorCode.java
  deal-service/src/main/java/com/wesell/dealservice/facade/MainPageFacadeService.java
  deal-service/src/main/java/com/wesell/dealservice/service/CategoryService.java
  deal-service/src/main/java/com/wesell/dealservice/service/CategoryServiceImpl.java
  deal-service/src/main/java/com/wesell/dealservice/service/DealService.java
  deal-service/src/main/java/com/wesell/dealservice/service/DealServiceImpl.java
  front-server/.env
  front-server/package-lock.json
  front-server/package.json
  front-server/src/App.tsx
  front-server/src/pages/board/post/Post.tsx
  front-server/src/setupProxy.js
Labels: feat

#106 feat: OAuth2.0 설정 & 소셜 로그인 기능 구현(Kakao)
  .vscode/settings.json
  apigateway-server/src/main/resources/application.yml
  authentication-server/src/main/java/com/wesell/authenticationserver/controller/AuthController.java
  authentication-server/src/main/java/com/wesell/authenticationserver/controller/CorsTestController.java
  authentication-server/src/main/java/com/wesell/authenticationserver/global/config/KakaoFeignConfig.java
  authentication-server/src/main/java/com/wesell/authenticationserver/global/config/SecurityConfig.java
  authentication-server/src/main/java/com/wesell/authenticationserver/global/util/CustomConverter.java
  authentication-server/src/main/java/com/wesell/authenticationserver/service/AuthUserService.java
  authentication-server/src/main/java/com/wesell/authenticationserver/service/dto/oauth/KakaoAccount.java
  authentication-server/src/main/java/com/wesell/authenticationserver/service/dto/oauth/KakaoInfo.java
  authentication-server/src/main/java/com/wesell/authenticationserver/service/dto/oauth/KakaoToken.java
  authentication-server/src/main/java/com/wesell/authenticationserver/service/dto/oauth/Profile.java
  authentication-server/src/main/java/com/wesell/authenticationserver/service/feign/KakaoFeignClient.java
  authentication-server/src/main/java/com/wesell/authenticationserver/service/oauth/KakaoService.java
  authentication-server/src/main/resources/application.yml
  front-server/.gitignore
  front-server/package-lock.json
  front-server/package.json
  front-server/src/App.tsx
  front-server/src/apis/index.ts
  front-server/src/components/Loading/index.tsx
  front-server/src/components/Loading/style.css
  front-server/src/constant/index.tsx
  front-server/src/pages/Authentication/index.tsx
  front-server/src/pages/Social/kakao/index.tsx
  front-server/src/setupProxy.js
Labels: feat

#111 [User] - exception handler 구현하기
  authentication-server/src/main/java/com/wesell/authenticationserver/controller/AdminAuthController.java
  authentication-server/src/main/java/com/wesell/authenticationserver/controller/dto/request/CreateUserRequestDto.java
  deal-service/src/main/java/com/wesell/dealservice/feignClient/UserFeignClient.java
  deal-service/src/main/resources/application.yml
  user-service/src/main/java/com/wesell/userservice/controller/AdminUserController.java
  user-service/src/main/java/com/wesell/userservice/controller/FeignController.java
  user-service/src/main/java/com/wesell/userservice/controller/UserController.java
  user-service/src/main/java/com/wesell/userservice/domain/repository/UserRepository.java
  user-service/src/main/java/com/wesell/userservice/dto/response/ErrorResponseDto.java
  user-service/src/main/java/com/wesell/userservice/error/exception/ErrorCode.java
  user-service/src/main/java/com/wesell/userservice/error/exception/GlobalExceptionHandler.java
  user-service/src/main/java/com/wesell/userservice/error/exception/UserNotFoundException.java
  user-service/src/main/java/com/wesell/userservice/exception/UserNotFoundException.java
  user-service/src/main/java/com/wesell/userservice/service/AdminFeignService.java
  user-service/src/main/java/com/wesell/userservice/service/UserService.java
  user-service/src/main/java/com/wesell/userservice/service/feign/AuthServerFeignClient.java
  user-service/src/test/java/com/wesell/userservice/domain/repository/UserRepositoryTest.java
Labels: feat

#117 [Auth/User] - 회원 탈퇴 처리하기
  authentication-server/src/main/java/com/wesell/authenticationserver/controller/AuthFeignController.java
  authentication-server/src/main/java/com/wesell/authenticationserver/controller/CertificatePhoneController.java
  authentication-server/src/main/java/com/wesell/authenticationserver/controller/FindIDFeignController.java
  authentication-server/src/main/java/com/wesell/authenticationserver/controller/FindPWDFeignController.java
  authentication-server/src/main/java/com/wesell/authenticationserver/controller/UserDeleteController.java
  authentication-server/src/main/java/com/wesell/authenticationserver/controller/usercontroller/EmailInfoController.java
  authentication-server/src/main/java/com/wesell/authenticationserver/domain/entity/AuthUser.java
  authentication-server/src/main/java/com/wesell/authenticationserver/domain/repository/UserDeleteRepository.java
  authentication-server/src/main/java/com/wesell/authenticationserver/global/util/CustomConverter.java
  authentication-server/src/main/java/com/wesell/authenticationserver/service/userservice/UserDeleteService.java
  authentication-server/src/main/resources/application.yml
  user-service/src/main/java/com/wesell/userservice/controller/UserController.java
  user-service/src/main/java/com/wesell/userservice/dto/feigndto/SignUpResponseDto.java
  user-service/src/main/java/com/wesell/userservice/error/exception/SuccessCode.java
Labels: feat

#118 feat: [Front & Auth] 회원가입&로그인 api 통신 테스트 및 로직 수정
  apigateway-server/src/main/resources/application.yml
  authentication-server/src/main/java/com/wesell/authenticationserver/controller/AuthController.java
  authentication-server/src/main/java/com/wesell/authenticationserver/controller/CertificatePhoneController.java
  authentication-server/src/main/java/com/wesell/authenticationserver/controller/response/ErrorControllerAdvisor.java
  authentication-server/src/main/java/com/wesell/authenticationserver/controller/response/ResponseDto.java
  authentication-server/src/main/java/com/wesell/authenticationserver/global/util/CustomCookie.java
  authentication-server/src/main/java/com/wesell/authenticationserver/service/AuthUserService.java
  authentication-server/src/main/java/com/wesell/authenticationserver/service/feign/UserServiceFeignClient.java
  front-server/package-lock.json
  front-server/package.json
  front-server/src/App.tsx
  front-server/src/apis/index.ts
  front-server/src/apis/request/auth/sign-in.request.dto.ts
  front-server/src/apis/request/auth/sign-up.request.dto.ts
  front-server/src/apis/response/auth/sign-in.response.dto.ts
  front-server/src/apis/response/response.dto.ts
  front-server/src/components/ButtonBox/index.tsx
  front-server/src/components/ButtonBox/style.css
  front-server/src/components/CheckBox/index.tsx
  front-server/src/components/CheckBox/style.css
  front-server/src/components/InputBox/index.tsx
  front-server/src/components/InputBox/style.css
  front-server/src/pages/Authentication/index.tsx
  front-server/src/pages/Authentication/style.css
  front-server/src/pages/Social/kakao/index.tsx
  front-server/src/pages/Test/index.tsx
  front-server/src/pages/board/post/Post.tsx
  front-server/src/setupProxy.js
  front-server/src/types/index.ts
  user-service/src/main/java/com/wesell/userservice/controller/DupNicknameCheckController.java
  user-service/src/main/java/com/wesell/userservice/controller/UserController.java
  user-service/src/main/java/com/wesell/userservice/domain/repository/NicknameCheckRepository.java
  user-service/src/main/java/com/wesell/userservice/service/DupNicknameCheckService.java
Labels: feat

#125 ref: RTR(Refresh Token Rotation) 방식 도입
  authentication-server/build.gradle
  authentication-server/src/main/java/com/wesell/authenticationserver/controller/AuthController.java
  authentication-server/src/main/java/com/wesell/authenticationserver/controller/CertificatePhoneController.java
  authentication-server/src/main/java/com/wesell/authenticationserver/controller/response/ErrorCode.java
  authentication-server/src/main/java/com/wesell/authenticationserver/global/util/CustomCookie.java
  authentication-server/src/main/java/com/wesell/authenticationserver/service/AuthUserService.java
  authentication-server/src/main/java/com/wesell/authenticationserver/service/token/TokenProvider.java
  authentication-server/src/main/resources/application-test.yml
  authentication-server/src/test/java/com/wesell/authenticationserver/service/CookieUtilTest.java
  authentication-server/src/test/java/com/wesell/authenticationserver/service/TokenProviderTest.java
Labels: test, re-factoring

#128 fix: gateway 권한 확인 및 필터 기능 수정
  apigateway-server/build.gradle
  apigateway-server/src/main/java/com/wesell/apigatewayserver/filter/AuthorizationCheckFilter.java
  apigateway-server/src/main/java/com/wesell/apigatewayserver/filter/GlobalFilter.java
  apigateway-server/src/main/java/com/wesell/apigatewayserver/filter/UserDetailsImpl.java
  apigateway-server/src/main/java/com/wesell/apigatewayserver/filter/UserDetailsServiceImpl.java
  apigateway-server/src/main/java/com/wesell/apigatewayserver/global/TokenValidator.java
  apigateway-server/src/main/java/com/wesell/apigatewayserver/global/config/ReactiveSecurityConfig.java
  apigateway-server/src/main/java/com/wesell/apigatewayserver/global/config/SecurityConfig.java
  apigateway-server/src/main/java/com/wesell/apigatewayserver/global/token/TokenProperties.java
  apigateway-server/src/main/java/com/wesell/apigatewayserver/global/token/TokenProvider.java
  apigateway-server/src/main/java/com/wesell/apigatewayserver/response/ErrorCode.java
  apigateway-server/src/main/java/com/wesell/apigatewayserver/response/ErrorResponseDto.java
  apigateway-server/src/main/resources/application.yml
  apigateway-server/src/main/resources/bootstrap.yml
  authentication-server/src/main/java/com/wesell/authenticationserver/controller/UserDeleteController.java
  authentication-server/src/main/java/com/wesell/authenticationserver/controller/response/ErrorCode.java
  config-server/src/main/resources/application.yml
  front-server/src/apis/index.ts
  front-server/src/constant/response-code.enum.ts
  front-server/src/pages/Authentication/index.tsx
Labels: wontfix

#130 fix: front 측 access-token 재발급 로직 구현
  apigateway-server/src/main/java/com/wesell/apigatewayserver/global/config/ReactiveSecurityConfig.java
  apigateway-server/src/main/java/com/wesell/apigatewayserver/global/token/TokenProvider.java
  authentication-server/.gitignore
  authentication-server/src/main/java/com/wesell/authenticationserver/controller/AuthController.java
  authentication-server/src/main/java/com/wesell/authenticationserver/global/util/CustomCookie.java
  authentication-server/src/main/java/com/wesell/authenticationserver/service/token/TokenProvider.java
  authentication-server/src/main/resources/application.yml
  config-server/src/main/resources/application.yml
  front-server/src/apis/index.ts
Labels: wontfix

#132 충돌 방지 전 프론트 코드 머지
  deal-service/src/main/java/com/wesell/dealservice/controller/CategoryController.java
  deal-service/src/main/java/com/wesell/dealservice/controller/DealController.java
  deal-service/src/main/java/com/wesell/dealservice/domain/dto/response/MainPagePostResponseDto.java
  deal-service/src/main/java/com/wesell/dealservice/domain/dto/response/MyPostListResponseDto.java
  deal-service/src/main/java/com/wesell/dealservice/domain/dto/response/PostInfoResponseDto.java
  deal-service/src/main/java/com/wesell/dealservice/domain/repository/DealRepository.java
  deal-service/src/main/java/com/wesell/dealservice/service/DealServiceImpl.java
  front-server/package-lock.json
  front-server/package.json
  front-server/src/App.tsx
  front-server/src/components/PostContentBox/index.tsx
  front-server/src/constant/index.tsx
  front-server/src/pages/board/detail/index.css
  front-server/src/pages/board/detail/index.tsx
  front-server/src/pages/board/edit/index.tsx
  front-server/src/pages/board/wirte/Write.css
  front-server/src/pages/board/wirte/Write.tsx
Labels: bug

#134 fix: localdatetime 수정
  config-server/.gitignore
  deal-service/src/main/java/com/wesell/dealservice/controller/CategoryController.java
  deal-service/src/main/java/com/wesell/dealservice/controller/DealController.java
  deal-service/src/main/java/com/wesell/dealservice/domain/dto/request/UploadDealPostRequestDto.java
  deal-service/src/main/java/com/wesell/dealservice/domain/dto/response/MyPostListResponseDto.java
  deal-service/src/main/java/com/wesell/dealservice/domain/dto/response/PostInfoResponseDto.java
  deal-service/src/main/java/com/wesell/dealservice/domain/entity/DealPost.java
  deal-service/src/main/java/com/wesell/dealservice/service/DealServiceImpl.java
  front-server/src/App.tsx
  front-server/src/constant/index.tsx
  front-server/src/pages/board/write/Write.css
  front-server/src/pages/board/write/Write.tsx
Labels: re-factoring

#136 feat: [front] 마이페이지 회원 정보 페이지 구현
  apigateway-server/.gitignore
  apigateway-server/src/main/java/com/wesell/apigatewayserver/filter/AuthorizationCheckFilter.java
  apigateway-server/src/main/java/com/wesell/apigatewayserver/filter/GlobalFilter.java
  apigateway-server/src/main/java/com/wesell/apigatewayserver/global/config/CustomReactiveAuthenticationManager.java
  apigateway-server/src/main/java/com/wesell/apigatewayserver/global/config/ReactiveSecurityConfig.java
  apigateway-server/src/main/java/com/wesell/apigatewayserver/global/enum_/Role.java
  apigateway-server/src/main/java/com/wesell/apigatewayserver/global/token/TokenProvider.java
  apigateway-server/src/main/java/com/wesell/apigatewayserver/response/ErrorCode.java
  apigateway-server/src/main/java/com/wesell/apigatewayserver/response/ErrorResponseDto.java
  apigateway-server/src/main/java/com/wesell/apigatewayserver/response/exception/CustomException.java
  apigateway-server/src/main/java/com/wesell/apigatewayserver/response/exception/TokenExpiredException.java
  apigateway-server/src/main/resources/application.yml
  authentication-server/build.gradle
  authentication-server/src/main/java/com/wesell/authenticationserver/controller/response/ErrorCode.java
  authentication-server/src/main/java/com/wesell/authenticationserver/service/AuthUserService.java
  authentication-server/src/main/resources/application.yml
  config-server/src/main/resources/application.yml
  front-server/package-lock.json
  front-server/package.json
  front-server/src/App.tsx
  front-server/src/apis/index.ts
  front-server/src/apis/response/mypage/idnex.ts
  front-server/src/apis/response/mypage/mypage.response.dto.ts
  front-server/src/components/ButtonBox/index.tsx
  front-server/src/components/ButtonBox/style.css
  front-server/src/components/InputBox/index.tsx
  front-server/src/components/aBox/index.tsx
  front-server/src/components/aBox/style.css
  front-server/src/constant/index.tsx
  front-server/src/index.tsx
  front-server/src/layouts/Comtainer/index.tsx
  front-server/src/layouts/Header/index.tsx
  front-server/src/pages/Authentication/index.tsx
  front-server/src/pages/Mypage/index.tsx
  front-server/src/pages/Mypage/style.css
  front-server/src/pages/withdraw/index.tsx
  front-server/src/pages/withdraw/style.css
  front-server/src/stores/index.tsx
  user-service/src/main/java/com/wesell/userservice/controller/FeignController.java
  user-service/src/main/java/com/wesell/userservice/controller/UserController.java
  user-service/src/main/java/com/wesell/userservice/controller/response/CustomException.java
  user-service/src/main/java/com/wesell/userservice/controller/response/NewResponseDto.java
  user-service/src/main/java/com/wesell/userservice/service/feign/AuthServerFeignClient.java
Labels: feat

#137 feat : [front] 아이디찾기 및 비밀번호 찾기,수정구현
  admin-service/src/main/java/com/wesell/adminservice/controller/AdminController.java
  authentication-server/src/main/java/com/wesell/authenticationserver/domain/repository/FindIDRepository.java
  authentication-server/src/main/java/com/wesell/authenticationserver/domain/repository/FindPWDRepository.java
  authentication-server/src/main/java/com/wesell/authenticationserver/global/util/SmsUtil.java
  authentication-server/src/main/java/com/wesell/authenticationserver/service/userservice/FindPWDFeignService.java
  front-server/.idea/workspace.xml
  front-server/src/App.tsx
  front-server/src/constant/index.tsx
  front-server/src/pages/UserfindbyPwd/EmailfindComponent.tsx
  front-server/src/pages/UserfindbyPwd/FoundSmsComponent.tsx
  front-server/src/pages/UserfindbyPwd/PasswordUpdateComponent.tsx
  front-server/src/pages/Userfindbyid/FoundEmailComponent.tsx
  front-server/src/pages/Userfindbyid/UuidComponent.tsx
  user-service/src/main/java/com/wesell/userservice/service/UserService.java
Labels: feat

#141 feat: 메인페이지 , 상세보기 50%달성
  .gitignore
  deal-service/src/main/java/com/wesell/dealservice/controller/DealController.java
  deal-service/src/main/java/com/wesell/dealservice/domain/dto/response/MainPagePostResponseDto.java
  deal-service/src/main/java/com/wesell/dealservice/domain/entity/DealPost.java
  deal-service/src/main/java/com/wesell/dealservice/domain/entity/Image.java
  deal-service/src/main/java/com/wesell/dealservice/domain/repository/ImageRepository.java
  deal-service/src/main/java/com/wesell/dealservice/domain/repository/read/DealPostReadRepository.java
  deal-service/src/main/java/com/wesell/dealservice/feignClient/UserFeignClient.java
  deal-service/src/main/java/com/wesell/dealservice/service/DealService.java
  deal-service/src/main/java/com/wesell/dealservice/service/DealServiceImpl.java
  deal-service/src/main/resources/application.yml
  deal-service/src/main/resources/bootstrap.yml
  front-server/.eslintrc.js
  front-server/package-lock.json
  front-server/package.json
  front-server/src/App.tsx
  front-server/src/components/Search/FilterForm.tsx
  front-server/src/components/Search/style.css
  front-server/src/constant/index.tsx
  front-server/src/pages/Main/index.tsx
  front-server/src/pages/Main/style.css
  front-server/src/pages/Search/index.tsx
  front-server/src/pages/board/detail/index.css
  front-server/src/pages/board/detail/index.tsx
  front-server/src/pages/board/write/Write.tsx
  front-server/src/stores2/index.tsx
  user-service/src/main/resources/application.yml
  user-service/src/main/resources/bootstrap.yml
Labels: front-end

#146 Redis 환경설정 및 구현
  authentication-server/src/main/java/com/wesell/authenticationserver/AuthenticationServerApplication.java
  authentication-server/src/main/java/com/wesell/authenticationserver/controller/AuthController.java
  authentication-server/src/main/java/com/wesell/authenticationserver/controller/AuthFeignController.java
  authentication-server/src/main/java/com/wesell/authenticationserver/domain/entity/AuthUser.java
  authentication-server/src/main/java/com/wesell/authenticationserver/global/util/SmsUtil.java
  authentication-server/src/main/resources/application.yml
  deal-service/build.gradle
  deal-service/src/main/java/com/wesell/dealservice/controller/DealController.java
  deal-service/src/main/java/com/wesell/dealservice/domain/dto/response/MyPostListResponseDto.java
  deal-service/src/main/java/com/wesell/dealservice/domain/dto/response/PageResponseDto.java
  deal-service/src/main/java/com/wesell/dealservice/domain/entity/DealPost.java
  deal-service/src/main/java/com/wesell/dealservice/redis/RedisCacheConfig.java
  deal-service/src/main/java/com/wesell/dealservice/redis/RedisConfig.java
  deal-service/src/main/java/com/wesell/dealservice/service/DealService.java
  deal-service/src/main/java/com/wesell/dealservice/service/DealServiceImpl.java
  deal-service/src/main/java/com/wesell/dealservice/service/FileUploadService.java
  deal-service/src/main/java/com/wesell/dealservice/util/Consumer.java
  deal-service/src/main/resources/application.yml
  front-server/.idea/workspace.xml
  front-server/package-lock.json
Labels: feat

#151 feat: css 구현
  deal-service/src/main/java/com/wesell/dealservice/domain/dto/response/PostInfoResponseDto.java
  front-server/src/App.tsx
  front-server/src/pages/Main/assets/image.png
  front-server/src/pages/Main/index.tsx
  front-server/src/pages/Main/style.css
  front-server/src/pages/board/detail/index.css
  front-server/src/pages/board/detail/index.tsx
  front-server/src/pages/board/write/Write.tsx
  front-server/src/pages/search/assets/icon.png
  front-server/src/pages/search/category.tsx
  front-server/src/pages/search/style.css
  front-server/src/pages/search/title.tsx
Labels: feat, front-end

#153 Feat 139 - [Front] 관리자페이지 회원목록 기능구현
  admin-service/src/main/java/com/wesell/adminservice/controller/AdminController.java
  admin-service/src/main/java/com/wesell/adminservice/service/VersionService.java
  apigateway-server/.gitignore
  apigateway-server/src/main/java/com/wesell/apigatewayserver/filter/GlobalFilter.java
  apigateway-server/src/main/java/com/wesell/apigatewayserver/global/config/ReactiveSecurityConfig.java
  apigateway-server/src/main/java/com/wesell/apigatewayserver/response/ErrorResponseDto.java
  apigateway-server/src/main/resources/application.yml
  authentication-server/.gitignore
  config-server/src/main/resources/application.properties
  deal-service/src/main/java/com/wesell/dealservice/domain/dto/request/RequestCreateDealPostDto.java
  deal-service/src/main/java/com/wesell/dealservice/feignClient/UserFeignClient.java
  front-server/package-lock.json
  front-server/package.json
  front-server/public/index.html
  front-server/src/App.tsx
  front-server/src/pages/AdminSite/UserManagementComponent.tsx
  front-server/src/pages/AdminSite/VersionupdateComponent.tsx
  front-server/src/pages/AdminUsers/AdminUsersComponent.tsx
  front-server/src/pages/UserfindbyPwd/EmailfindComponent.tsx
  front-server/src/pages/UserfindbyPwd/FoundSmsComponent.tsx
  front-server/src/pages/UserfindbyPwd/PasswordUpdateComponent.tsx
  front-server/src/pages/Userfindbyid/FoundEmailComponent.tsx
  front-server/src/pages/Userfindbyid/UuidComponent.tsx
Labels: feat

#155 fix: 통합 테스트 1차 완료
  apigateway-server/src/main/resources/application.yml
  authentication-server/src/main/java/com/wesell/authenticationserver/global/util/SmsUtil.java
  deal-service/src/main/java/com/wesell/dealservice/domain/repository/read/DealPostReadRepository.java
  deal-service/src/main/java/com/wesell/dealservice/feignClient/UserFeignClient.java
  deal-service/src/main/java/com/wesell/dealservice/service/DealServiceImpl.java
  front-server/package-lock.json
  front-server/package.json
  front-server/src/App.tsx
  front-server/src/pages/board/detail/index.css
  front-server/src/pages/board/detail/index.tsx
Labels: wontfix

#160 발표 전 머지
  deal-service/src/main/java/com/wesell/dealservice/controller/DealController.java
  deal-service/src/main/java/com/wesell/dealservice/service/DealServiceImpl.java
  front-server/src/components/card/Card.css
  front-server/src/components/card/Card.js
  front-server/src/pages/Main/index.tsx
  front-server/src/pages/Main/style.css
  front-server/src/pages/board/detail/index.tsx
  front-server/src/pages/board/edit/index.css
  front-server/src/pages/board/edit/index.tsx
  front-server/src/pages/board/write/Write.tsx
  front-server/src/pages/search/category.tsx
  front-server/src/pages/search/style.css
  front-server/src/pages/search/title.tsx
Labels: bug, re-factoring

#163 비밀번호 찾기 시 소셜 로그인 구분하기
  authentication-server/src/main/java/com/wesell/authenticationserver/controller/FindPWDFeignController.java
  authentication-server/src/main/java/com/wesell/authenticationserver/controller/response/ErrorCode.java
  authentication-server/src/main/java/com/wesell/authenticationserver/global/util/SmsUtil.java
  authentication-server/src/main/java/com/wesell/authenticationserver/service/userservice/FindPWDFeignService.java
  authentication-server/src/main/resources/application.yml
  front-server/.idea/workspace.xml
  front-server/src/pages/UserfindbyPwd/PasswordUpdateComponent.tsx
Labels: feat
