Repository playdata-final-project-team/Wesell, pull requests merged in 2023-11, with the labels that each got.

#1 Category entity 생성
  deal-service/src/main/java/com/wesell/dealservice/domain/entity/Category.java
  deal-service/src/main/java/com/wesell/dealservice/domain/entity/Product.java
  deal-service/src/main/resources/application.yml
Labels: feat

#4 feat: 인증인가 엔티티 생성 및 레포지토리 생성
  authentication-server/.gitignore
  authentication-server/build.gradle
  authentication-server/src/main/java/com/wesell/authenticationserver/domain/entity/Authentication.java
  authentication-server/src/main/java/com/wesell/authenticationserver/domain/enum_/Role.java
  authentication-server/src/main/java/com/wesell/authenticationserver/domain/repository/AuthRepository.java
  authentication-server/src/main/resources/application.properties
  authentication-server/src/main/resources/application.yml
Labels: feat

#7 feat: 사이트 설정 등록 기능구현
  admin-service/src/main/java/com/wesell/adminservice/config/ModelMapperConfig.java
  admin-service/src/main/java/com/wesell/adminservice/controller/AdminController.java
  admin-service/src/main/java/com/wesell/adminservice/domain/dto/RequestAdminDto.java
  admin-service/src/main/java/com/wesell/adminservice/domain/dto/ResponseAdminDto.java
  admin-service/src/main/java/com/wesell/adminservice/domain/entity/SiteConfig.java
  admin-service/src/main/java/com/wesell/adminservice/domain/repository/AdminRepository.java
  admin-service/src/main/java/com/wesell/adminservice/service/AdminService.java
  admin-service/src/main/resources/static/css/main.css
  admin-service/src/main/resources/static/js/main.js
  admin-service/src/main/resources/templates/index.html
Labels: feat

#10 fix: 회원 엔티티 수정2
  user-service/src/main/java/com/wesell/userservice/domain/entity/User.java
  user-service/src/main/resources/application.yml
Labels: feat

#9 feat: 사이트 정보 조회기능 구현
  admin-service/build.gradle
  admin-service/src/main/java/com/wesell/adminservice/controller/AdminController.java
  admin-service/src/main/java/com/wesell/adminservice/service/AdminService.java
  admin-service/src/main/resources/application.yml
Labels: feat

#11 feat: spring-security 설정
  authentication-server/src/main/java/com/wesell/authenticationserver/domain/entity/Authentication.java
  authentication-server/src/main/java/com/wesell/authenticationserver/global/config/SecurityConfig.java
  authentication-server/src/main/java/com/wesell/authenticationserver/global/config/SwaggerConfig.java
  authentication-server/src/main/resources/application.yml
Labels: feat

#16 fix: 회원 레퍼지토리 수정
  user-service/build.gradle
  user-service/src/main/java/com/wesell/userservice/domain/entity/User.java
  user-service/src/main/java/com/wesell/userservice/domain/repository/UserRepository.java
  user-service/src/test/java/com/wesell/userservice/domain/repository/UserRepositoryTest.java
Labels: feat

#13 feat: 거래글 등록 기능 구현
  deal-service/src/main/java/com/wesell/dealservice/controller/DealController.java
  deal-service/src/main/java/com/wesell/dealservice/domain/SaleStatus.java
  deal-service/src/main/java/com/wesell/dealservice/domain/dto/request/RequestCreateDealPostDto.java
  deal-service/src/main/java/com/wesell/dealservice/domain/entity/Category.java
  deal-service/src/main/java/com/wesell/dealservice/domain/entity/DealPost.java
  deal-service/src/main/java/com/wesell/dealservice/domain/entity/Product.java
  deal-service/src/main/java/com/wesell/dealservice/domain/repository/DealRepository.java
  deal-service/src/main/java/com/wesell/dealservice/service/DealService.java
  deal-service/src/main/java/com/wesell/dealservice/service/DealServiceImpl.java
  deal-service/src/main/resources/application.yml
Labels: feat

#17 feat: 사이트 설정 수정 기능
  admin-service/src/main/java/com/wesell/adminservice/controller/AdminController.java
  admin-service/src/main/java/com/wesell/adminservice/service/AdminService.java
Labels: feat

#19 feat: 회원 목록 조회 기능
  admin-service/build.gradle
  admin-service/src/main/java/com/wesell/adminservice/AdminServiceApplication.java
  admin-service/src/main/java/com/wesell/adminservice/controller/AdminController.java
  admin-service/src/main/java/com/wesell/adminservice/domain/dto/SiteConfigRequestDto.java
  admin-service/src/main/java/com/wesell/adminservice/domain/dto/SiteConfigResponseDto.java
  admin-service/src/main/java/com/wesell/adminservice/domain/dto/UserListResponseDto.java
  admin-service/src/main/java/com/wesell/adminservice/feignClient/UserFeignClient.java
  admin-service/src/main/java/com/wesell/adminservice/service/AdminService.java
Labels: feat

#20 feat: 회원 목록 조회 구현
  user-service/src/main/java/com/wesell/userservice/controller/UserController.java
  user-service/src/main/java/com/wesell/userservice/domain/entity/User.java
  user-service/src/main/java/com/wesell/userservice/domain/repository/UserRepository.java
  user-service/src/main/java/com/wesell/userservice/dto/responseDto.java
  user-service/src/main/java/com/wesell/userservice/exception/UserNotFoundException.java
  user-service/src/main/java/com/wesell/userservice/service/UserService.java
  user-service/src/main/resources/application.yml
  user-service/src/test/java/com/wesell/userservice/domain/repository/UserRepositoryTest.java
Labels: feat

#21 feat: 거래 게시글 수정
  deal-service/build.gradle
  deal-service/src/main/java/com/wesell/dealservice/DealServiceApplication.java
  deal-service/src/main/java/com/wesell/dealservice/controller/CategoryController.java
  deal-service/src/main/java/com/wesell/dealservice/controller/DealController.java
  deal-service/src/main/java/com/wesell/dealservice/domain/dto/request/CreateCategoryRequestDto.java
  deal-service/src/main/java/com/wesell/dealservice/domain/dto/request/CreateDealPostRequestDto.java
  deal-service/src/main/java/com/wesell/dealservice/domain/dto/request/EditPostRequestDto.java
  deal-service/src/main/java/com/wesell/dealservice/domain/dto/request/RequestCreateDealPostDto.java
  deal-service/src/main/java/com/wesell/dealservice/domain/dto/response/EditPostResponseDto.java
  deal-service/src/main/java/com/wesell/dealservice/domain/entity/Category.java
  deal-service/src/main/java/com/wesell/dealservice/domain/entity/DealPost.java
  deal-service/src/main/java/com/wesell/dealservice/domain/repository/CategoryRepository.java
  deal-service/src/main/java/com/wesell/dealservice/domain/repository/DealRepository.java
  deal-service/src/main/java/com/wesell/dealservice/service/CategoryService.java
  deal-service/src/main/java/com/wesell/dealservice/service/DealService.java
  deal-service/src/main/java/com/wesell/dealservice/service/DealServiceImpl.java
  deal-service/src/main/resources/application.yml
Labels: feat

#23 feat:회원가입기능구현
  user-service/src/main/java/com/wesell/userservice/controller/UserController.java
  user-service/src/main/java/com/wesell/userservice/domain/entity/User.java
  user-service/src/main/java/com/wesell/userservice/domain/repository/UserRepository.java
  user-service/src/main/java/com/wesell/userservice/dto/RequestSignupDTO.java
  user-service/src/main/java/com/wesell/userservice/dto/responseDto.java
  user-service/src/main/java/com/wesell/userservice/service/UserService.java
Labels: feat

#25 feat: 회원 탈퇴 기능 구현
  user-service/src/main/java/com/wesell/userservice/controller/UserController.java
  user-service/src/main/java/com/wesell/userservice/domain/repository/UserRepository.java
  user-service/src/main/java/com/wesell/userservice/service/UserService.java
  user-service/src/main/resources/application.yml
  user-service/src/test/java/com/wesell/userservice/domain/repository/UserRepositoryTest.java
Labels: feat

#24 feat: 회원수정구현
  user-service/src/main/java/com/wesell/userservice/controller/UserController.java
  user-service/src/main/java/com/wesell/userservice/domain/repository/UserRepository.java
  user-service/src/main/java/com/wesell/userservice/dto/SignupRequestDto.java
  user-service/src/main/java/com/wesell/userservice/dto/responseDto.java
  user-service/src/main/java/com/wesell/userservice/service/UserService.java
  user-service/src/test/java/com/wesell/userservice/domain/repository/UserRepositoryTest.java
Labels: feat

#26 feat: JWT 생성 로직 구현
  authentication-server/build.gradle
  authentication-server/src/main/java/com/wesell/authenticationserver/controller/AuthController.java
  authentication-server/src/main/java/com/wesell/authenticationserver/domain/entity/TokenInfo.java
  authentication-server/src/main/java/com/wesell/authenticationserver/domain/repository/AuthUserRepository.java
  authentication-server/src/main/java/com/wesell/authenticationserver/domain/repository/TokenInfoRepository.java
  authentication-server/src/main/java/com/wesell/authenticationserver/domain/token/TokenProperties.java
  authentication-server/src/main/java/com/wesell/authenticationserver/dto/GeneratedTokenDto.java
  authentication-server/src/main/java/com/wesell/authenticationserver/dto/request/LoginUserRequestDto.java
  authentication-server/src/main/java/com/wesell/authenticationserver/global/util/CustomConverter.java
  authentication-server/src/main/java/com/wesell/authenticationserver/global/util/CustomCookie.java
  authentication-server/src/main/java/com/wesell/authenticationserver/global/util/CustomPasswordEncoder.java
  authentication-server/src/main/java/com/wesell/authenticationserver/service/AuthUserService.java
  authentication-server/src/main/java/com/wesell/authenticationserver/service/TokenInfoService.java
  authentication-server/src/main/java/com/wesell/authenticationserver/service/token/AccessTokenProvider.java
  authentication-server/src/main/java/com/wesell/authenticationserver/service/token/RefreshTokenProvider.java
  authentication-server/src/main/java/com/wesell/authenticationserver/service/token/TokenProvider.java
  authentication-server/src/main/resources/application.yml
Labels: feat

#27 feat: 게시글 수정, 삭제, 게시글 상세 보기
  deal-service/src/main/java/com/wesell/dealservice/DealServiceApplication.java
  deal-service/src/main/java/com/wesell/dealservice/controller/CategoryController.java
  deal-service/src/main/java/com/wesell/dealservice/controller/DealController.java
  deal-service/src/main/java/com/wesell/dealservice/domain/dto/request/CreateDealPostRequestDto.java
  deal-service/src/main/java/com/wesell/dealservice/domain/dto/response/EditPostResponseDto.java
  deal-service/src/main/java/com/wesell/dealservice/domain/dto/response/PostInfoResponseDto.java
  deal-service/src/main/java/com/wesell/dealservice/domain/entity/DealPost.java
  deal-service/src/main/java/com/wesell/dealservice/domain/repository/DealRepository.java
  deal-service/src/main/java/com/wesell/dealservice/feignClient/UserFeignClient.java
  deal-service/src/main/java/com/wesell/dealservice/service/DealService.java
  deal-service/src/main/java/com/wesell/dealservice/service/DealServiceImpl.java
Labels: feat

#28 feat: JWT 쿠키 생성 및 전달 기능 구현
  authentication-server/src/main/java/com/wesell/authenticationserver/controller/AuthController.java
  authentication-server/src/main/java/com/wesell/authenticationserver/dto/LoginSuccessDto.java
  authentication-server/src/main/java/com/wesell/authenticationserver/global/util/CustomCookie.java
  authentication-server/src/main/java/com/wesell/authenticationserver/global/util/CustomPasswordEncoder.java
  authentication-server/src/main/java/com/wesell/authenticationserver/response/ErrorCode.java
  authentication-server/src/main/java/com/wesell/authenticationserver/response/ErrorControllerAdvisor.java
  authentication-server/src/main/java/com/wesell/authenticationserver/response/ErrorResponseDto.java
  authentication-server/src/main/java/com/wesell/authenticationserver/response/SuccessCode.java
  authentication-server/src/main/java/com/wesell/authenticationserver/service/AuthUserService.java
  authentication-server/src/main/java/com/wesell/authenticationserver/service/token/TokenProvider.java
Labels: feat

#29 feat: 회원 로그인 기능 구현
  authentication-server/src/main/java/com/wesell/authenticationserver/controller/AuthController.java
  authentication-server/src/main/java/com/wesell/authenticationserver/dto/request/LoginUserRequestDto.java
  authentication-server/src/main/java/com/wesell/authenticationserver/global/util/CustomCookie.java
Labels: feat

#30 fix: AuthUserEntity 권한 변경 메서드 정의
  authentication-server/src/main/java/com/wesell/authenticationserver/domain/entity/AuthUser.java
Labels: wontfix

#31 feat: deal service에 닉네임 전송 기능
  deal-service/src/main/java/com/wesell/dealservice/error/ErrorCode.java
  deal-service/src/main/java/com/wesell/dealservice/error/exception/CustomException.java
  user-service/src/main/java/com/wesell/userservice/controller/UserController.java
  user-service/src/main/java/com/wesell/userservice/domain/repository/UserRepository.java
  user-service/src/main/java/com/wesell/userservice/service/UserService.java
Labels: feat

#32 fix: 회원정보 수정 기능 수정 및 클래스명 변경
  user-service/src/main/java/com/wesell/userservice/controller/UserController.java
  user-service/src/main/java/com/wesell/userservice/domain/entity/User.java
  user-service/src/main/java/com/wesell/userservice/domain/repository/UserRepository.java
  user-service/src/main/java/com/wesell/userservice/dto/SignupRequestDto.java
  user-service/src/main/java/com/wesell/userservice/dto/request/SignupRequestDto.java
  user-service/src/main/java/com/wesell/userservice/dto/response/ResponseDto.java
  user-service/src/main/java/com/wesell/userservice/service/UserService.java
  user-service/src/main/resources/application.yml
Labels: wontfix

#33 feat: 커스텀 예외 처리 기능
  deal-service/src/main/java/com/wesell/dealservice/controller/CategoryController.java
  deal-service/src/main/java/com/wesell/dealservice/controller/DealController.java
  deal-service/src/main/java/com/wesell/dealservice/domain/entity/DealPost.java
  deal-service/src/main/java/com/wesell/dealservice/dto/request/CreateCategoryRequestDto.java
  deal-service/src/main/java/com/wesell/dealservice/dto/request/CreateDealPostRequestDto.java
  deal-service/src/main/java/com/wesell/dealservice/dto/request/EditPostRequestDto.java
  deal-service/src/main/java/com/wesell/dealservice/dto/response/EditPostResponseDto.java
  deal-service/src/main/java/com/wesell/dealservice/dto/response/ErrorResponseDto.java
  deal-service/src/main/java/com/wesell/dealservice/dto/response/PostInfoResponseDto.java
  deal-service/src/main/java/com/wesell/dealservice/error/ControllerAdvisor.java
  deal-service/src/main/java/com/wesell/dealservice/error/ErrorCode.java
  deal-service/src/main/java/com/wesell/dealservice/error/exception/CustomException.java
  deal-service/src/main/java/com/wesell/dealservice/service/CategoryService.java
  deal-service/src/main/java/com/wesell/dealservice/service/DealService.java
  deal-service/src/main/java/com/wesell/dealservice/service/DealServiceImpl.java
Labels: feat

#34 feat: 프론트에 전송할 responseDto 구현
  deal-service/src/main/java/com/wesell/dealservice/controller/CategoryController.java
  deal-service/src/main/java/com/wesell/dealservice/controller/DealController.java
  deal-service/src/main/java/com/wesell/dealservice/domain/entity/Category.java
  deal-service/src/main/java/com/wesell/dealservice/domain/entity/DealPost.java
  deal-service/src/main/java/com/wesell/dealservice/domain/repository/CategoryRepository.java
  deal-service/src/main/java/com/wesell/dealservice/domain/repository/DealRepository.java
  deal-service/src/main/java/com/wesell/dealservice/dto/response/MainPageCategoryResponseDto.java
  deal-service/src/main/java/com/wesell/dealservice/dto/response/MainPagePostResponseDto.java
  deal-service/src/main/java/com/wesell/dealservice/dto/response/MyPostListResponseDto.java
  deal-service/src/main/java/com/wesell/dealservice/service/CategoryService.java
  deal-service/src/main/java/com/wesell/dealservice/service/CategoryServiceImpl.java
  deal-service/src/main/java/com/wesell/dealservice/service/DealService.java
  deal-service/src/main/java/com/wesell/dealservice/service/DealServiceImpl.java
Labels: feat

#35 fix: 회원 목록 조회 기능 수정
  admin-service/src/main/java/com/wesell/adminservice/AdminServiceApplication.java
  admin-service/src/main/java/com/wesell/adminservice/controller/AdminController.java
  admin-service/src/main/java/com/wesell/adminservice/domain/dto/request/SiteConfigRequestDto.java
  admin-service/src/main/java/com/wesell/adminservice/domain/dto/response/SiteConfigResponseDto.java
  admin-service/src/main/java/com/wesell/adminservice/domain/dto/response/UserListResponseDto.java
  admin-service/src/main/java/com/wesell/adminservice/feignClient/UserFeignClient.java
  admin-service/src/main/java/com/wesell/adminservice/service/AdminService.java
Labels: feat

#36 feat:마이페이지 사용자정보보기구현
  user-service/src/main/java/com/wesell/userservice/controller/UserController.java
  user-service/src/main/java/com/wesell/userservice/domain/repository/UserRepository.java
  user-service/src/main/java/com/wesell/userservice/dto/response/MypageResponseDto.java
  user-service/src/main/java/com/wesell/userservice/dto/response/ResponseDto.java
  user-service/src/main/java/com/wesell/userservice/service/UserService.java
Labels: feat

#38 feat: 회원 권한 변경 기능
  admin-service/src/main/java/com/wesell/adminservice/controller/AdminController.java
  admin-service/src/main/java/com/wesell/adminservice/domain/dto/request/ChangeRoleRequestDto.java
  admin-service/src/main/java/com/wesell/adminservice/domain/enum_/Role.java
  admin-service/src/main/java/com/wesell/adminservice/feignClient/AuthFeignClient.java
  admin-service/src/main/java/com/wesell/adminservice/service/AdminService.java
  authentication-server/src/main/java/com/wesell/authenticationserver/controller/AdminAuthController.java
  authentication-server/src/main/java/com/wesell/authenticationserver/domain/repository/AdminAuthUserRepository.java
  authentication-server/src/main/java/com/wesell/authenticationserver/dto/request/AdminAuthRoleRequestDto.java
  authentication-server/src/main/java/com/wesell/authenticationserver/service/AdminAuthService.java
Labels: feat

#37 ref: 코드 리팩토링
  deal-service/src/main/java/com/wesell/dealservice/controller/DealController.java
  deal-service/src/main/java/com/wesell/dealservice/domain/entity/DealPost.java
  deal-service/src/main/java/com/wesell/dealservice/domain/repository/DealRepository.java
  deal-service/src/main/java/com/wesell/dealservice/dto/FacadeDto.java
  deal-service/src/main/java/com/wesell/dealservice/dto/response/ErrorResponseDto.java
  deal-service/src/main/java/com/wesell/dealservice/error/ControllerAdvisor.java
  deal-service/src/main/java/com/wesell/dealservice/error/ErrorCode.java
  deal-service/src/main/java/com/wesell/dealservice/error/exception/CustomException.java
  deal-service/src/main/java/com/wesell/dealservice/facade/MainPageFacadeService.java
  deal-service/src/main/java/com/wesell/dealservice/service/CategoryService.java
  deal-service/src/main/java/com/wesell/dealservice/service/CategoryServiceImpl.java
  deal-service/src/main/java/com/wesell/dealservice/service/DealService.java
  deal-service/src/main/java/com/wesell/dealservice/service/DealServiceImpl.java
Labels: re-factoring

#40 feat: 판매 글 조회 기능
  admin-service/src/main/java/com/wesell/adminservice/controller/AdminController.java
  admin-service/src/main/java/com/wesell/adminservice/domain/dto/response/PostListResponseDto.java
  admin-service/src/main/java/com/wesell/adminservice/domain/enum_/SaleStatus.java
  admin-service/src/main/java/com/wesell/adminservice/feignClient/DealFeignClient.java
  admin-service/src/main/java/com/wesell/adminservice/service/AdminService.java
  apigateway-server/build.gradle
  apigateway-server/src/main/resources/application.yml
Labels: feat

#39 [Auth] - 권한 확인 커스텀 필터 구현
  authentication-server/src/main/java/com/wesell/authenticationserver/controller/AuthController.java
  authentication-server/src/main/java/com/wesell/authenticationserver/domain/entity/TokenInfo.java
  authentication-server/src/main/java/com/wesell/authenticationserver/domain/repository/AuthUserRepository.java
  authentication-server/src/main/java/com/wesell/authenticationserver/dto/GeneratedTokenDto.java
  authentication-server/src/main/java/com/wesell/authenticationserver/filter/JwtAuthenticationFilter.java
  authentication-server/src/main/java/com/wesell/authenticationserver/global/util/CustomConverter.java
  authentication-server/src/main/java/com/wesell/authenticationserver/global/util/CustomCookie.java
  authentication-server/src/main/java/com/wesell/authenticationserver/response/CustomException.java
  authentication-server/src/main/java/com/wesell/authenticationserver/response/ErrorCode.java
  authentication-server/src/main/java/com/wesell/authenticationserver/response/ErrorControllerAdvisor.java
  authentication-server/src/main/java/com/wesell/authenticationserver/response/ErrorResponseDto.java
  authentication-server/src/main/java/com/wesell/authenticationserver/service/AuthUserService.java
  authentication-server/src/main/java/com/wesell/authenticationserver/service/TokenInfoService.java
  authentication-server/src/main/java/com/wesell/authenticationserver/service/UserDetailsImpl.java
  authentication-server/src/main/java/com/wesell/authenticationserver/service/UserDetailsServiceImpl.java
  authentication-server/src/main/java/com/wesell/authenticationserver/service/token/TokenProvider.java
Labels: feat

#42 feat: 판매 글 강제삭제 기능
  admin-service/src/main/java/com/wesell/adminservice/controller/AdminController.java
  admin-service/src/main/java/com/wesell/adminservice/domain/dto/request/AdminAuthIsForcedRequestDto.java
  admin-service/src/main/java/com/wesell/adminservice/domain/dto/response/AdminAuthIsForcedResponseDto.java
  admin-service/src/main/java/com/wesell/adminservice/feignClient/AuthFeignClient.java
  admin-service/src/main/java/com/wesell/adminservice/feignClient/DealFeignClient.java
  admin-service/src/main/java/com/wesell/adminservice/service/AdminService.java
  authentication-server/src/main/java/com/wesell/authenticationserver/controller/AdminAuthController.java
  authentication-server/src/main/java/com/wesell/authenticationserver/dto/request/AdminAuthIsForcedRequestDto.java
  authentication-server/src/main/java/com/wesell/authenticationserver/dto/response/AdminAuthIsForcedResponseDto.java
  authentication-server/src/main/java/com/wesell/authenticationserver/service/AdminAuthService.java
Labels: feat

#41 feat: 회원 강제탈퇴 기능
  admin-service/src/main/java/com/wesell/adminservice/controller/AdminController.java
  admin-service/src/main/java/com/wesell/adminservice/domain/dto/request/SiteConfigRequestDto.java
  admin-service/src/main/java/com/wesell/adminservice/domain/dto/response/SiteConfigResponseDto.java
  admin-service/src/main/java/com/wesell/adminservice/domain/entity/SiteConfig.java
  admin-service/src/main/java/com/wesell/adminservice/feignClient/UserFeignClient.java
  admin-service/src/main/java/com/wesell/adminservice/service/AdminService.java
Labels: feat

#51 feat: 관리자페이지 회원 목록 조회 관련 Feign 서비스 구현
  authentication-server/src/main/java/com/wesell/authenticationserver/controller/AuthFeignController.java
  authentication-server/src/main/java/com/wesell/authenticationserver/dto/feign/AuthUserListFeignResponseDto.java
  authentication-server/src/main/java/com/wesell/authenticationserver/global/util/CustomConverter.java
  authentication-server/src/main/java/com/wesell/authenticationserver/service/AuthUserService.java
Labels: feat

#60 fix: 사이트 설정 기능 수정
  admin-service/src/main/java/com/wesell/adminservice/controller/AdminController.java
  admin-service/src/main/java/com/wesell/adminservice/domain/dto/response/UserListResponseDto.java
  admin-service/src/main/java/com/wesell/adminservice/domain/entity/SiteConfig.java
  admin-service/src/main/java/com/wesell/adminservice/domain/repository/AdminRepository.java
  admin-service/src/main/java/com/wesell/adminservice/dto/request/AdminAuthIsForcedRequestDto.java
  admin-service/src/main/java/com/wesell/adminservice/dto/request/ChangeRoleRequestDto.java
  admin-service/src/main/java/com/wesell/adminservice/dto/request/SiteConfigRequestDto.java
  admin-service/src/main/java/com/wesell/adminservice/dto/response/AdminAuthIsForcedResponseDto.java
  admin-service/src/main/java/com/wesell/adminservice/dto/response/PostListResponseDto.java
  admin-service/src/main/java/com/wesell/adminservice/dto/response/SiteConfigResponseDto.java
  admin-service/src/main/java/com/wesell/adminservice/dto/response/UserListResponseDto.java
  admin-service/src/main/java/com/wesell/adminservice/feignClient/AuthFeignClient.java
  admin-service/src/main/java/com/wesell/adminservice/feignClient/DealFeignClient.java
  admin-service/src/main/java/com/wesell/adminservice/feignClient/UserFeignClient.java
  admin-service/src/main/java/com/wesell/adminservice/service/AdminService.java
Labels: feat

#66 feat: s3 연동하여 이미지 업로드
  deal-service/build.gradle
  deal-service/src/main/java/com/wesell/dealservice/DealServiceApplication.java
  deal-service/src/main/java/com/wesell/dealservice/config/S3Config.java
  deal-service/src/main/java/com/wesell/dealservice/controller/DealController.java
  deal-service/src/main/java/com/wesell/dealservice/controller/FileUploadController.java
  deal-service/src/main/java/com/wesell/dealservice/domain/entity/DealPost.java
  deal-service/src/main/java/com/wesell/dealservice/dto/facade/MainPageInfoFacadeDto.java
  deal-service/src/main/java/com/wesell/dealservice/dto/request/UploadDealPostRequestDto.java
  deal-service/src/main/java/com/wesell/dealservice/dto/response/PostInfoResponseDto.java
  deal-service/src/main/java/com/wesell/dealservice/facade/MainPageFacadeService.java
  deal-service/src/main/java/com/wesell/dealservice/service/DealService.java
  deal-service/src/main/java/com/wesell/dealservice/service/DealServiceImpl.java
  deal-service/src/main/java/com/wesell/dealservice/service/FileUploadService.java
  deal-service/src/main/resources/application.yml
  image-server/build.gradle
  image-server/src/main/java/com/wesell/imageserver/ImageServerApplication.java
  image-server/src/main/java/com/wesell/imageserver/config/S3Config.java
  image-server/src/main/java/com/wesell/imageserver/controller/UploadController.java
  image-server/src/main/java/com/wesell/imageserver/domain/dto/request/FileUploadRequestDto.java
  image-server/src/main/java/com/wesell/imageserver/domain/entity/Image.java
  image-server/src/main/java/com/wesell/imageserver/domain/repository/ImageRepository.java
  image-server/src/main/java/com/wesell/imageserver/service/AmazonS3ResourceStorage.java
  image-server/src/main/java/com/wesell/imageserver/service/FileUploadService.java
  image-server/src/main/java/com/wesell/imageserver/service/MultiPartUtil.java
  image-server/src/main/resources/application-db.yml
  image-server/src/main/resources/application.yml
Labels: feat

#68 feat: 아이디 찾기 기능 구현
  user-service/src/main/java/com/wesell/userservice/controller/FindIDController.java
  user-service/src/main/java/com/wesell/userservice/domain/repository/UserRepository.java
  user-service/src/main/java/com/wesell/userservice/dto/response/FindIDResponseDto.java
  user-service/src/main/java/com/wesell/userservice/global/util/SmsUtil.java
  user-service/src/main/java/com/wesell/userservice/service/AdminFeignService.java
  user-service/src/main/java/com/wesell/userservice/service/FindIDService.java
  user-service/src/main/java/com/wesell/userservice/service/UserService.java
  user-service/src/main/resources/application.yml
  user-service/src/test/java/com/wesell/userservice/domain/repository/UserRepositoryTest.java
Labels: feat

#72 Feat: [User] - 마이페이지 email항목 Feign기능 구현
  authentication-server/src/main/java/com/wesell/authenticationserver/controller/usercontroller/EmailInfoController.java
  authentication-server/src/main/java/com/wesell/authenticationserver/domain/repository/EmailInfoRepository/EmailInfoRepository.java
  authentication-server/src/main/java/com/wesell/authenticationserver/dto/response/userdto/EmailInfoDto.java
  authentication-server/src/main/java/com/wesell/authenticationserver/service/userservice/EmailService.java
  user-service/src/main/java/com/wesell/userservice/UserServiceApplication.java
  user-service/src/main/java/com/wesell/userservice/controller/FeignController.java
  user-service/src/main/java/com/wesell/userservice/controller/UserController.java
  user-service/src/main/java/com/wesell/userservice/dto/feigndto/EmailInfoDto.java
  user-service/src/main/java/com/wesell/userservice/dto/request/SignupRequestDto.java
  user-service/src/main/java/com/wesell/userservice/dto/response/MypageResponseDto.java
  user-service/src/main/java/com/wesell/userservice/service/EmailService.java
  user-service/src/main/java/com/wesell/userservice/service/UserService.java
  user-service/src/main/java/com/wesell/userservice/service/feign/AuthServerFeignClient.java
  user-service/src/main/resources/application.yml
Labels: feat

#75 Feat: [Deal/User] - 닉네임 받기
  user-service/src/main/java/com/wesell/userservice/controller/UserController.java
  user-service/src/main/java/com/wesell/userservice/domain/repository/UserRepository.java
  user-service/src/main/java/com/wesell/userservice/service/UserService.java
Labels: feat

#76 fix: feign 기능 수정
  admin-service/src/main/java/com/wesell/adminservice/controller/AdminController.java
  admin-service/src/main/java/com/wesell/adminservice/domain/enum_/Role.java
  admin-service/src/main/java/com/wesell/adminservice/dto/response/PostListResponseDto.java
  admin-service/src/main/resources/application.yml
Labels: re-factoring

#73 test: jwt filter 검증 & fix: error 발생 부분 로직 수정.
  apigateway-server/src/main/java/com/wesell/apigatewayserver/filter/AuthorizationCheckFilter.java
  apigateway-server/src/main/java/com/wesell/apigatewayserver/filter/UserDetailsImpl.java
  apigateway-server/src/main/java/com/wesell/apigatewayserver/global/TokenValidator.java
  apigateway-server/src/main/java/com/wesell/apigatewayserver/global/config/SecurityConfig.java
Labels: test, wontfix

#78 feat: 유저 엔티티 수정
  user-service/src/main/java/com/wesell/userservice/domain/entity/User.java
  user-service/src/main/java/com/wesell/userservice/dto/response/ResponseDto.java
  user-service/src/main/resources/application.yml
Labels: feat

#79 fix: [Auth/User] - Entity 수정
  authentication-server/src/main/java/com/wesell/authenticationserver/controller/AdminAuthController.java
  authentication-server/src/main/java/com/wesell/authenticationserver/domain/entity/AuthUser.java
  authentication-server/src/main/java/com/wesell/authenticationserver/domain/repository/AdminAuthUserRepository.java
  authentication-server/src/main/java/com/wesell/authenticationserver/domain/repository/AuthUserRepository.java
  authentication-server/src/main/java/com/wesell/authenticationserver/service/AdminAuthService.java
  authentication-server/src/main/java/com/wesell/authenticationserver/service/AuthUserService.java
Labels: wontfix

#80 feat: 검색 기능 (이미지 db 저장 추가 구현)
  deal-service/src/main/java/com/wesell/dealservice/controller/DealController.java
  deal-service/src/main/java/com/wesell/dealservice/controller/FileUploadController.java
  deal-service/src/main/java/com/wesell/dealservice/domain/entity/Category.java
  deal-service/src/main/java/com/wesell/dealservice/domain/entity/DealPost.java
  deal-service/src/main/java/com/wesell/dealservice/domain/entity/Image.java
  deal-service/src/main/java/com/wesell/dealservice/domain/repository/DealRepository.java
  deal-service/src/main/java/com/wesell/dealservice/domain/repository/ImageRepository.java
  deal-service/src/main/java/com/wesell/dealservice/dto/request/UploadDealPostRequestDto.java
  deal-service/src/main/java/com/wesell/dealservice/dto/response/PostInfoResponseDto.java
  deal-service/src/main/java/com/wesell/dealservice/facade/MainPageFacadeService.java
  deal-service/src/main/java/com/wesell/dealservice/feignClient/UserFeignClient.java
  deal-service/src/main/java/com/wesell/dealservice/service/DealService.java
  deal-service/src/main/java/com/wesell/dealservice/service/DealServiceImpl.java
  deal-service/src/main/java/com/wesell/dealservice/service/FileUploadService.java
Labels: feat

#83 fix:회원 권한 변경 수정
  admin-service/build.gradle
  admin-service/src/main/java/com/wesell/adminservice/config/ModelMapperConfig.java
  admin-service/src/main/java/com/wesell/adminservice/controller/AdminController.java
  admin-service/src/main/java/com/wesell/adminservice/dto/response/PostListResponseDto.java
  admin-service/src/main/java/com/wesell/adminservice/dto/response/UserListResponseDto.java
  admin-service/src/main/java/com/wesell/adminservice/feignClient/AuthFeignClient.java
  admin-service/src/main/java/com/wesell/adminservice/service/AdminService.java
  admin-service/src/main/resources/application.yml
  authentication-server/src/main/java/com/wesell/authenticationserver/controller/AdminAuthController.java
  authentication-server/src/main/java/com/wesell/authenticationserver/service/AuthUserService.java
  authentication-server/src/main/java/com/wesell/authenticationserver/service/dto/response/AdminAuthIsForcedResponseDto.java
  authentication-server/src/main/java/com/wesell/authenticationserver/service/dto/response/AdminAuthResponseDto.java
Labels: re-factoring

#85 feat: Dealservice feign 닉네임 받기 구현
  deal-service/src/main/java/com/wesell/dealservice/controller/usercontroller/NicknameController.java
  deal-service/src/main/java/com/wesell/dealservice/dto/userdto/NicknameDto.java
  deal-service/src/main/java/com/wesell/dealservice/feignClient/UserFeignClient.java
  user-service/src/main/java/com/wesell/userservice/controller/UserController.java
Labels: feat

#86 fix: feign client 연결 수정
  deal-service/src/main/java/com/wesell/dealservice/controller/usercontroller/NicknameController.java
  deal-service/src/main/java/com/wesell/dealservice/dto/response/PostInfoResponseDto.java
  deal-service/src/main/java/com/wesell/dealservice/dto/userdto/NicknameDto.java
  deal-service/src/main/java/com/wesell/dealservice/feignClient/UserFeignClient.java
  user-service/src/main/java/com/wesell/userservice/controller/UserControllerByChaelim.java
Labels: feat
